<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<EnableDefaultItems>false</EnableDefaultItems>
	<IsPackable>true</IsPackable>
	<IncludeBuildOutput>false</IncludeBuildOutput>
	<NoDefaultExcludes>true</NoDefaultExcludes>
	<SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
	<PackageId>Barisozy.Clean.Architecture.Template</PackageId>
	<Authors>barisozy</Authors>
	<Description>A .NET 10 Clean Architecture API solution template.</Description>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	<PackageTags>dotnet-new;template;clean-architecture;web-api</PackageTags>
	<PackageType>Template</PackageType>
	<RepositoryType>git</RepositoryType>
	<RepositoryUrl>https://github.com/barisozy/clean-architecture</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
	<None Include="README.md" Pack="true" PackagePath="\" />
	<Content Include="**/*"
			  Exclude=".containers/**;.git/**;.vs/**;README.md;CleanArchitecture.Template.csproj;artifacts/**;packaging/**;**/bin/**;**/obj/**;**/TestResults/**;.github/workflows/publish-nuget.yml;**/*.user;**/*.suo;**/*.userosscache">
	  <Pack>true</Pack>
	  <PackagePath>content/%(RecursiveDir)%(Filename)%(Extension)</PackagePath>
	</Content>
  </ItemGroup>
</Project>
